language: node_js
node_js:
  - "6"
  - "4"
cache:
  directories:
    # cache node modules
    - node_modules
install:
  - npm install
  - npm prune

script:
  - npm test

# Allow Travis tests to run in containers.
sudo: false
