language: node_js

# Allow Travis tests to run in containers.
sudo: false

node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install -g npm@5
  - npm --version

install:
  - npm install
  - npm run bootstrap

script:
  - npm test
